export const THONG_TIN_SINH_VIEN = "THONG_TIN_SINH_VIEN";
export const THEM_SINH_VIEN = "THEM_SINH_VIEN ";
export const XOA_SINH_VIEN = "XOA_SINH_VIEN";
export const SUA_SINH_VIEN = "SUA_SINH_VIEN";
export const CAP_NHAT_SINH_VIEN = "CAP_NHAT_SINH_VIEN";
export const TIM_KIEM_SINH_VIEN = "TIM_KIEM_SINH_VIEN";
